# position at signal generated
float64 a1
float64 a2
float64 a3
float64 a4
float64 a5
float64 a6
float64 a7

# position at signal received
float64 b1
float64 b2
float64 b3
float64 b4
float64 b5
float64 b6
float64 b7
---
uint16 signal_response_code
float64 a1
float64 a2
float64 a3
float64 a4
float64 a5
float64 a6
float64 a7