#!/usr/bin/python3

import sys
import rospy
import moveit_commander
import moveit_msgs.msg
import geometry_msgs.msg
from std_msgs.msg import String
from math import pi


moveit_commander.roscpp_initialize(sys.argv)
rospy.init_node('iiwa_tesla_move_route')
rate = rospy.Rate(1)

robot = moveit_commander.RobotCommander()
scene = moveit_commander.PlanningSceneInterface()
group_name = 'manipulator'
move_group = moveit_commander.MoveGroupCommander(group_name)

display_trajectory_publisher = rospy.Publisher('/move_group/display_planned_path', moveit_msgs.msg.DisplayTrajectory, queue_size=20)


move_group.set_planning_time(1)
move_group.set_planner_id('RRTConnectkConfigDefault')
eef = 'iiwa_link_ee'
move_group.set_end_effector_link(eef)

current_joint = move_group.get_current_joint_values()
home_joint = [0.0 for x in range(7)]

move_group.set_start_state_to_current_state()
move_group.set_joint_value_target(home_joint)
move_group.go(wait=True)

home_joint_2 = home_joint
home_joint_2[1] = 14.0 *(pi/180)
home_joint_2[3] = -75.0 *(pi/180)
home_joint_2[5] = 38.0 *(pi/180)

move_group.set_start_state_to_current_state()
move_group.set_joint_value_target(home_joint_2)
move_group.go(wait=True)

point0 = move_group.get_current_pose(eef)

# points out of loop in list
# compute_cartesian_path uses a waypoints list to go through ;)


while not rospy.is_shutdown():
    print('waiting for new goal...')

    # loop through list and call methods like move() clear(),...

    point1 = point0
    point1.Pose.position.x += 50
    move_group.set_start_state_to_current_state()
    move_group.set_pose_target(point1, eef)
    # move_group.compute_cartesian_path()
    move_group.go(wait=True)
    move_group.clear_pose_targets()

    point2 = point1
    point2.Pose.position.y += 50
    move_group.set_start_state_to_current_state()
    move_group.set_pose_target(point2, eef)
    # move_group.compute_cartesian_path()
    move_group.go(wait=True)
    move_group.clear_pose_targets()

    point3 = point2
    point3.Pose.position.x -= 50
    move_group.set_start_state_to_current_state()
    move_group.set_pose_target(point3, eef)
    # move_group.compute_cartesian_path()
    move_group.go(wait=True)
    move_group.clear_pose_targets()

    move_group.set_start_state_to_current_state()
    move_group.set_pose_target(point0, eef)
    # move_group.compute_cartesian_path()
    move_group.go(wait=True)
    move_group.clear_pose_targets()

    rate.sleep()
    pass
