#! /usr/bin/env python

import rospy
from iiwa_tesla_msgs.srv import Signal, SignalResponse

def handle_signal(req):
    if True:
        return SignalResponse(True)

def send_signal_server():
    rospy.init_node('SendSignal', anonymous=True)
    s = rospy.Service('send_signal', Signal, handle_signal)
    rospy.spin()

if __name__ == '__main__':
    send_signal_server()