#! /usr/bin/env python3

import rospy
from iiwa_msgs.msg import JointPosition
from iiwa_tesla_msgs.msg import InterruptSignal

signal_position = JointPosition()
signal_position.position.a1 = 0.0
signal_position.position.a2 = 0.5
signal_position.position.a3 = 0.0
signal_position.position.a4 = 0.0
signal_position.position.a5 = 0.0
signal_position.position.a6 = 0.0
signal_position.position.a7 = 0.0

def publish_interrupt(signal_position=signal_position):
    print('signal server launched')
    while not rospy.is_shutdown():
        signal_publisher.publish(
            rospy.get_param('/tesla/signal/crack_signal'),
            signal_position.position.a1,
            signal_position.position.a2,
            signal_position.position.a3,
            signal_position.position.a4,
            signal_position.position.a5,
            signal_position.position.a6,
            signal_position.position.a7
            )
        rate.sleep()
        

rospy.init_node('PublishSignal', anonymous=True)
rate = rospy.Rate(10)
signal_publisher = rospy.Publisher('/tesla/Crack', InterruptSignal, queue_size=1)
publish_interrupt()